DROP TABLE IF EXISTS Addres;
create table base_country (
	id integer primary key,
	iso2 char(2),
	iso3 char(3),
	name_en varchar(64),
	name_fr varchar(64),
	name_de varchar(64)
);


INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (1, 'AF', 'AFG', 'Afghanistan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (2, 'AX', 'ALA', 'Åland Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (4, 'DZ', 'DZA', 'Algeria (El Djazaïr)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (3, 'AL', 'ALB', 'Albania', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (5, 'AS', 'ASM', 'American Samoa', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (6, 'AD', 'AND', 'Andorra', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (7, 'AO', 'AGO', 'Angola', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (8, 'AI', 'AIA', 'Anguilla', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (9, 'AQ', 'ATA', 'Antarctica', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (10, 'AG', 'ATG', 'Antigua and Barbuda', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (11, 'AR', 'ARG', 'Argentina', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (12, 'AM', 'ARM', 'Armenia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (13, 'AW', 'ABW', 'Aruba', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (14, 'AU', 'AUS', 'Australia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (15, 'AT', 'AUT', 'Austria', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (16, 'AZ', 'AZE', 'Azerbaijan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (17, 'BS', 'BHS', 'Bahamas', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (18, 'BH', 'BHR', 'Bahrain', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (19, 'BD', 'BGD', 'Bangladesh', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (20, 'BB', 'BRB', 'Barbados', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (21, 'BY', 'BLR', 'Belarus', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (22, 'BE', 'BEL', 'Belgium', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (23, 'BZ', 'BLZ', 'Belize', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (24, 'BJ', 'BEN', 'Benin', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (25, 'BM', 'BMU', 'Bermuda', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (26, 'BT', 'BTN', 'Bhutan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (27, 'BO', 'BOL', 'Bolivia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (28, 'BA', 'BIH', 'Bosnia and Herzegovina', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (29, 'BW', 'BWA', 'Botswana', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (30, 'BV', 'BVT', 'Bouvet Island', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (31, 'BR', 'BRA', 'Brazil', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (32, 'IO', 'IOT', 'British Indian Ocean Territory', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (33, 'BN', 'BRN', 'Brunei Darussalam', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (34, 'BG', 'BGR', 'Bulgaria', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (35, 'BF', 'BFA', 'Burkina Faso', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (36, 'BI', 'BDI', 'Burundi', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (37, 'KH', 'KHM', 'Cambodia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (38, 'CM', 'CMR', 'Cameroon', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (39, 'CA', 'CAN', 'Canada', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (40, 'CV', 'CPV', 'Cape Verde', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (41, 'KY', 'CYM', 'Cayman Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (42, 'CF', 'CAF', 'Central African Republic', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (43, 'TD', 'TCD', 'Chad (T''Chad)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (44, 'CL', 'CHL', 'Chile', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (45, 'CN', 'CHN', 'China', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (46, 'CX', 'CXR', 'Christmas Island', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (47, 'CC', 'CCK', 'Cocos (Keeling) Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (48, 'CO', 'COL', 'Colombia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (49, 'KM', 'COM', 'Comoros', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (50, 'CG', 'COG', 'Congo, Republic Of', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (51, 'CD', 'COD', 'Congo, The Democratic Republic of the (formerly Zaire)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (52, 'CK', 'COK', 'Cook Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (53, 'CR', 'CRI', 'Costa Rica', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (54, 'CI', 'CIV', 'CÔte D''Ivoire (Ivory Coast)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (55, 'HR', 'HRV', 'Croatia (hrvatska)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (56, 'CU', 'CUB', 'Cuba', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (57, 'CY', 'CYP', 'Cyprus', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (58, 'CZ', 'CZE', 'Czech Republic', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (59, 'DK', 'DNK', 'Denmark', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (60, 'DJ', 'DJI', 'Djibouti', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (61, 'DM', 'DMA', 'Dominica', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (62, 'DO', 'DOM', 'Dominican Republic', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (63, 'EC', 'ECU', 'Ecuador', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (64, 'EG', 'EGY', 'Egypt', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (65, 'SV', 'SLV', 'El Salvador', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (66, 'GQ', 'GNQ', 'Equatorial Guinea', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (67, 'ER', 'ERI', 'Eritrea', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (68, 'EE', 'EST', 'Estonia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (69, 'ET', 'ETH', 'Ethiopia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (70, 'FO', 'FRO', 'Faeroe Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (71, 'FK', 'FLK', 'Falkland Islands (Malvinas)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (72, 'FJ', 'FJI', 'Fiji', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (73, 'FI', 'FIN', 'Finland', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (74, 'FR', 'FRA', 'France', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (75, 'GF', 'GUF', 'French Guiana', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (76, 'PF', 'PYF', 'French Polynesia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (77, 'TF', 'ATF', 'French Southern Territories', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (78, 'GA', 'GAB', 'Gabon', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (79, 'GM', 'GMB', 'Gambia, The', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (80, 'GE', 'GEO', 'Georgia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (81, 'DE', 'DEU', 'Germany (Deutschland)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (82, 'GH', 'GHA', 'Ghana', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (83, 'GI', 'GIB', 'Gibraltar', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (84, 'GB', 'GBR', 'Great Britain', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (85, 'GR', 'GRC', 'Greece', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (86, 'GL', 'GRL', 'Greenland', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (87, 'GD', 'GRD', 'Grenada', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (88, 'GP', 'GLP', 'Guadeloupe', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (89, 'GU', 'GUM', 'Guam', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (90, 'GT', 'GTM', 'Guatemala', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (91, 'GN', 'GIN', 'Guinea', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (92, 'GW', 'GNB', 'Guinea-bissau', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (93, 'GY', 'GUY', 'Guyana', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (94, 'HT', 'HTI', 'Haiti', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (95, 'HM', 'HMD', 'Heard Island and Mcdonald Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (96, 'HN', 'HND', 'Honduras', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (97, 'HK', 'HKG', 'Hong Kong (Special Administrative Region of China)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (98, 'HU', 'HUN', 'Hungary', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (99, 'IS', 'ISL', 'Iceland', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (100, 'IN', 'IND', 'India', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (101, 'ID', 'IDN', 'Indonesia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (102, 'IR', 'IRN', 'Iran (Islamic Republic of Iran)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (103, 'IQ', 'IRQ', 'Iraq', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (104, 'IE', 'IRL', 'Ireland', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (105, 'IL', 'ISR', 'Israel', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (106, 'IT', 'ITA', 'Italy', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (107, 'JM', 'JAM', 'Jamaica', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (108, 'JP', 'JPN', 'Japan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (109, 'JO', 'JOR', 'Jordan (Hashemite Kingdom of Jordan)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (110, 'KZ', 'KAZ', 'Kazakhstan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (111, 'KE', 'KEN', 'Kenya', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (112, 'KI', 'KIR', 'Kiribati', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (113, 'KP', 'PRK', 'Korea (Democratic Peoples Republic pf [North] Korea)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (114, 'KR', 'KOR', 'Korea (Republic of [South] Korea)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (115, 'KW', 'KWT', 'Kuwait', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (116, 'KG', 'KGZ', 'Kyrgyzstan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (117, 'LA', 'LAO', 'Lao People''s Democratic Republic', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (118, 'LV', 'LVA', 'Latvia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (119, 'LB', 'LBN', 'Lebanon', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (120, 'LS', 'LSO', 'Lesotho', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (121, 'LR', 'LBR', 'Liberia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (122, 'LY', 'LBY', 'Libya (Libyan Arab Jamahirya)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (123, 'LI', 'LIE', 'Liechtenstein (Fürstentum Liechtenstein)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (124, 'LT', 'LTU', 'Lithuania', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (125, 'LU', 'LUX', 'Luxembourg', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (126, 'MO', 'MAC', 'Macao (Special Administrative Region of China)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (127, 'MK', 'MKD', 'Macedonia (Former Yugoslav Republic of Macedonia)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (128, 'MG', 'MDG', 'Madagascar', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (129, 'MW', 'MWI', 'Malawi', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (130, 'MY', 'MYS', 'Malaysia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (131, 'MV', 'MDV', 'Maldives', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (132, 'ML', 'MLI', 'Mali', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (133, 'MT', 'MLT', 'Malta', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (134, 'MH', 'MHL', 'Marshall Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (135, 'MQ', 'MTQ', 'Martinique', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (136, 'MR', 'MRT', 'Mauritania', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (137, 'MU', 'MUS', 'Mauritius', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (138, 'YT', 'MYT', 'Mayotte', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (139, 'MX', 'MEX', 'Mexico', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (140, 'FM', 'FSM', 'Micronesia (Federated States of Micronesia)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (141, 'MD', 'MDA', 'Moldova', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (142, 'MC', 'MCO', 'Monaco', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (143, 'MN', 'MNG', 'Mongolia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (144, 'MS', 'MSR', 'Montserrat', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (145, 'MA', 'MAR', 'Morocco', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (146, 'MZ', 'MOZ', 'Mozambique (Moçambique)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (147, 'MM', 'MMR', 'Myanmar (formerly Burma)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (148, 'NA', 'NAM', 'Namibia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (149, 'NR', 'NRU', 'Nauru', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (150, 'NP', 'NPL', 'Nepal', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (151, 'NL', 'NLD', 'Netherlands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (152, 'AN', 'ANT', 'Netherlands Antilles', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (153, 'NC', 'NCL', 'New Caledonia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (154, 'NZ', 'NZL', 'New Zealand', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (155, 'NI', 'NIC', 'Nicaragua', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (156, 'NE', 'NER', 'Niger', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (157, 'NG', 'NGA', 'Nigeria', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (158, 'NU', 'NIU', 'Niue', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (159, 'NF', 'NFK', 'Norfolk Island', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (160, 'MP', 'MNP', 'Northern Mariana Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (161, 'NO', 'NOR', 'Norway', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (162, 'OM', 'OMN', 'Oman', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (163, 'PK', 'PAK', 'Pakistan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (164, 'PW', 'PLW', 'Palau', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (165, 'PS', 'PSE', 'Palestinian Territories', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (166, 'PA', 'PAN', 'Panama', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (167, 'PG', 'PNG', 'Papua New Guinea', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (168, 'PY', 'PRY', 'Paraguay', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (169, 'PE', 'PER', 'Peru', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (170, 'PH', 'PHL', 'Philippines', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (171, 'PN', 'PCN', 'Pitcairn', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (172, 'PL', 'POL', 'Poland', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (173, 'PT', 'PRT', 'Portugal', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (174, 'PR', 'PRI', 'Puerto Rico', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (175, 'QA', 'QAT', 'Qatar', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (176, 'RE', 'REU', 'RÉunion', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (177, 'RO', 'ROU', 'Romania', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (178, 'RU', 'RUS', 'Russian Federation', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (179, 'RW', 'RWA', 'Rwanda', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (180, 'SH', 'SHN', 'Saint Helena', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (181, 'KN', 'KNA', 'Saint Kitts and Nevis', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (182, 'LC', 'LCA', 'Saint Lucia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (183, 'PM', 'SPM', 'Saint Pierre and Miquelon', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (184, 'VC', 'VCT', 'Saint Vincent and the Grenadines', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (185, 'WS', 'WSM', 'Samoa (formerly Western Samoa)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (186, 'SM', 'SMR', 'San Marino (Republic of)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (187, 'ST', 'STP', 'Sao Tome and Principe', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (188, 'SA', 'SAU', 'Saudi Arabia (Kingdom of Saudi Arabia)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (189, 'SN', 'SEN', 'Senegal', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (190, 'CS', 'SCG', 'Serbia and Montenegro (formerly Yugoslavia)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (191, 'SC', 'SYC', 'Seychelles', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (192, 'SL', 'SLE', 'Sierra Leone', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (193, 'SG', 'SGP', 'Singapore', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (194, 'SK', 'SVK', 'Slovakia (Slovak Republic)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (195, 'SI', 'SVN', 'Slovenia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (196, 'SB', 'SLB', 'Solomon Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (197, 'SO', 'SOM', 'Somalia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (198, 'ZA', 'ZAF', 'South Africa (zuid Afrika)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (199, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (200, 'ES', 'ESP', 'Spain (españa)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (201, 'LK', 'LKA', 'Sri Lanka', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (202, 'SD', 'SDN', 'Sudan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (203, 'SR', 'SUR', 'Suriname', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (204, 'SJ', 'SJM', 'Svalbard and Jan Mayen', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (205, 'SZ', 'SWZ', 'Swaziland', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (206, 'SE', 'SWE', 'Sweden', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (207, 'CH', 'CHE', 'Switzerland (Confederation of Helvetia)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (208, 'SY', 'SYR', 'Syrian Arab Republic', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (209, 'TW', 'TWN', 'Taiwan ("Chinese Taipei" for IOC)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (210, 'TJ', 'TJK', 'Tajikistan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (211, 'TZ', 'TZA', 'Tanzania', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (212, 'TH', 'THA', 'Thailand', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (213, 'TL', 'TLS', 'Timor-Leste (formerly East Timor)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (214, 'TG', 'TGO', 'Togo', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (215, 'TK', 'TKL', 'Tokelau', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (216, 'TO', 'TON', 'Tonga', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (217, 'TT', 'TTO', 'Trinidad and Tobago', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (218, 'TN', 'TUN', 'Tunisia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (219, 'TR', 'TUR', 'Turkey', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (220, 'TM', 'TKM', 'Turkmenistan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (221, 'TC', 'TCA', 'Turks and Caicos Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (222, 'TV', 'TUV', 'Tuvalu', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (223, 'UG', 'UGA', 'Uganda', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (224, 'UA', 'UKR', 'Ukraine', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (225, 'AE', 'ARE', 'United Arab Emirates', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (226, 'GB', 'GBR', 'United Kingdom (Great Britain)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (227, 'US', 'USA', 'United States', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (228, 'UM', 'UMI', 'United States Minor Outlying Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (229, 'UY', 'URY', 'Uruguay', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (230, 'UZ', 'UZB', 'Uzbekistan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (231, 'VU', 'VUT', 'Vanuatu', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (232, 'VA', 'VAT', 'Vatican City (Holy See)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (233, 'VE', 'VEN', 'Venezuela', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (234, 'VN', 'VNM', 'Viet Nam', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (235, 'VG', 'VGB', 'Virgin Islands, British', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (236, 'VI', 'VIR', 'Virgin Islands, U.S.', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (237, 'WF', 'WLF', 'Wallis and Futuna', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (238, 'EH', 'ESH', 'Western Sahara (formerly Spanish Sahara)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (239, 'YE', 'YEM', 'Yemen (Arab Republic)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (240, 'ZM', 'ZMB', 'Zambia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (241, 'ZW', 'ZWE', 'Zimbabwe', NULL);